/*
 * hub-kubernetes-agent
 *
 * an agent used to provision and configure Kubernetes resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"

	sw "github.com/appvia/hub-kubernetes-agent/go"
)

func Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		token := r.Header.Get("X-Token")

		if token == os.Getenv("AUTH_TOKEN") {
			log.Printf("Authenticated request")
			next.ServeHTTP(w, r)
		} else {
			http.Error(w, "Forbidden", http.StatusForbidden)
		}
	})
}

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	router.Use(Middleware)

	log.Fatal(http.ListenAndServe(":8080", router))
}
