/*
 * hub-kubernetes-agent
 *
 * an agent used to provision and configure Kubernetes resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"

	sw "github.com/appvia/hub-kubernetes-agent/go"
)

func Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		token := r.Header.Get("X-Token")

		if token == os.Getenv("AUTH_TOKEN") {
			log.Printf("Authenticated request")

			kubeToken := r.Header.Get("X-Kube-Token")
			server := r.Header.Get("X-Kube-API-URL")
			caCert := r.Header.Get("X-Kube-CA")

			if kubeToken == "" {
				log.Printf("No X-Kube-Token header provided")
				http.Error(w, "Forbidden", http.StatusForbidden)
			}
			if server == "" {
				log.Printf("No X-Kube-API-URL header provided")
				http.Error(w, "Forbidden", http.StatusForbidden)
			}
			if caCert == "" {
				log.Printf("No X-Kube-CA header provided")
				http.Error(w, "Forbidden", http.StatusForbidden)
			} else {
				next.ServeHTTP(w, r)
			}
		} else {
			http.Error(w, "Forbidden", http.StatusForbidden)
		}
	})
}


func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	router.Use(Middleware)

	log.Fatal(http.ListenAndServe(":8080", router))
}
