/*
 * hub-kubernetes-agent
 *
 * an agent used to provision and configure Kubernetes resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The resource specification of a service account
type ServiceAccountSpec struct {

	// The token associated with the service account
	Token string `json:"token,omitempty"`
}
