/*
 * hub-kubernetes-agent
 *
 * an agent used to provision and configure Kubernetes resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The resource definition for a list of Docker image tags
type ImageTagList struct {

	// A list of image tags
	Tags []string `json:",omitempty`
}
