/*
 * hub-kubernetes-agent
 *
 * an agent used to provision and configure Kubernetes resources
 *
 * API version: v1beta
 * Contact: support@appvia.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/hub.appvia.io/v1beta/",
		Index,
	},

	Route{
		"NamespacesList",
		strings.ToUpper("Get"),
		"/api/hub.appvia.io/v1beta/namespaces",
		NamespacesList,
	},

	Route{
		"NamespacesNameGet",
		strings.ToUpper("Get"),
		"/api/hub.appvia.io/v1beta/namespaces/{name}",
		NamespacesNameGet,
	},

	Route{
		"NamespacesNameDelete",
		strings.ToUpper("Delete"),
		"/api/hub.appvia.io/v1beta/namespaces/{name}",
		NamespacesNameDelete,
	},

	Route{
		"NamespacesNamePut",
		strings.ToUpper("Put"),
		"/api/hub.appvia.io/v1beta/namespaces/{name}",
		NamespacesNamePut,
	},

	Route{
		"ServiceAccountsNamespaceGet",
		strings.ToUpper("Get"),
		"/api/hub.appvia.io/v1beta/service-accounts/{namespace}",
		ServiceAccountsNamespaceGet,
	},

	Route{
		"ServiceAccountsNamespaceNameDelete",
		strings.ToUpper("Delete"),
		"/api/hub.appvia.io/v1beta/service-accounts/{namespace}/{name}",
		ServiceAccountsNamespaceNameDelete,
	},

	Route{
		"ServiceAccountsNamespaceNameGet",
		strings.ToUpper("Get"),
		"/api/hub.appvia.io/v1beta/service-accounts/{namespace}/{name}",
		ServiceAccountsNamespaceNameGet,
	},

	Route{
		"ServiceAccountsNamespaceNamePut",
		strings.ToUpper("Put"),
		"/api/hub.appvia.io/v1beta/service-accounts/{namespace}/{name}",
		ServiceAccountsNamespaceNamePut,
	},

	Route{
		"HealthzGet",
		strings.ToUpper("Get"),
		"/api/hub.appvia.io/v1beta/healthz",
		HealthzGet,
	},
}
