---
swagger: '2.0'
info:
  contact:
    name: admin@appvia.io
    url: https://github.com/appvia/hub-kubernetes-agent
    email: support@appvia.io
  description: an agent used to provision and configure Kubernetes resources
  title: hub-kubernetes-agent
  version: v1beta
schemes:
  - http
securityDefinitions:
  apikey:
    type: apiKey
    in: header
    name: Authorization
basePath: "/api/v1beta"
consumes:
  - application/json
produces:
  - application/json

responses:
  apierror:
    description: A generic erorr returned by the api
    schema:
      "$ref": "#/definitions/APIError"
  notfound:
    description: The resource does not exist
  service-account:
    description: Returning the status of a service account
    schema:
      "$ref": "#/definitions/ServiceAccount"
  service-accounts:
    description: Returning a list of service accounts
    schema:
      "$ref": "#/definitions/ServiceAccountList"
  namespace:
    description: The specification of a namespace in the cluster
    schema:
      "$ref": "#/definitions/Namespace"
  namespaces:
    description: A collection namespaces found in the cluster
    schema:
      "$ref": "#/definitions/NamespaceList"
  global-service-account:
    description: The name of the global service account that will be used to grant access to all namespaces created
    schema:
      "$ref": "#/definitions/GlobalServiceAccount"
  imageuri:
    description: The specification of a Docker image URI
    schema:
      "$ref": "#/definitions/ImageUri"
  imageuris:
    description: The specification of a Docker image URI
    schema:
      "$ref": "#/definitions/ImageUriList"
  imagetag:
    description: The specification of an image including a tag
    schema:
      "$ref": "#/definitions/ImageTag"
  imagetags:
    description: The specification of a list of images with tags
    schema:
      "$ref": "#/definitions/ImageTagList"

parameters:
  name:
    name: name
    description: The name of the namespace or service account you are acting upon
    in: path
    type: string
    required: true
  namespace:
    name: namespace
    description: The namespace of the service account
    in: path
    type: string
    required: true
  namespace-definition:
    name: namespace
    description: The definition of a namespace
    in: body
    schema:
      "$ref": "#/definitions/Namespace"
    required: true
  service-account-list:
    name: service-account-list
    description: A list of service accounts
    in: body
    schema:
      "$ref": "#/definitions/ServiceAccountSpec"
    required: true
  service-account-definition:
    name: service-account
    description: The definition of a service account
    in: body
    schema:
      "$ref": "#/definitions/ServiceAccount"
    required: true
  global-service-account:
    name: global-service-account
    description: The definition of a global service account
    in: body
    schema:
      "$ref": "#/definitions/GlobalServiceAccount"
    required: true
  imageuri:
    name: imageuri
    description: The Docker image URI
    in: body
    type: string
    required: true
  kube-token:
    name: X-Kube-Token
    description: A bearer authentication token used for requests to the Kubernetes API
    in: header
    type: string
    required: true
  kube-api-url:
    name: X-Kube-API-URL
    description: The URL of the Kubernetes API
    in: header
    type: string
    required: true
  kube-ca-cert:
    name: X-Kube-CA
    description: Base64 encoded CA certificate for requests to Kubernetes API
    in: header
    type: string
    required: true
paths:
  "/healthz":
    get:
      summary: Get health of Agent
      description: |
        Returns health and status information of the API daemon and
        related components such as the runtime.
      security: []
      tags:
        - health
      responses:
        '200':
          description: Success
        default:
          "$ref": "#/responses/apierror"

  "/service-accounts/{namespace}":
    parameters:
      - $ref: "#/parameters/kube-token"
      - $ref: "#/parameters/kube-api-url"
      - $ref: "#/parameters/kube-ca-cert"
    get:
      summary: Retrieves a list of service accounts from within the specified namespace
      description: |
        Used to retrieve a list of service accounts from within the specified namespace
      parameters:
        - "$ref": "#/parameters/namespace"
      responses:
        '200':
          "$ref": "#/responses/service-accounts"
        default:
          "$ref": "#/responses/apierror"

  "/service-accounts/{namespace}/{name}":
    parameters:
      - $ref: "#/parameters/kube-token"
      - $ref: "#/parameters/kube-api-url"
      - $ref: "#/parameters/kube-ca-cert"
    get:
      summary: Retrieves a service account
      description: |
        Retrieves a service account
      parameters:
        - "$ref": "#/parameters/namespace"
        - "$ref": "#/parameters/name"
      responses:
        '200':
          "$ref": "#/responses/service-account"
        '400':
          "$ref": "#/responses/apierror"
        '404':
          "$ref": "#/responses/apierror"
        default:
          "$ref": "#/responses/apierror"

    put:
      summary: Creates a service account
      description: |
        Used to create a service account within a specified namespace
      parameters:
        - "$ref": "#/parameters/namespace"
        - "$ref": "#/parameters/name"
        - "$ref": "#/parameters/service-account-definition"
      responses:
        '200':
          "$ref": "#/responses/service-account"
        default:
          "$ref": "#/responses/apierror"

    delete:
      summary: Deletes a service account from the namespace
      description: |
        Used to delete a service account
      parameters:
        - "$ref": "#/parameters/namespace"
        - "$ref": "#/parameters/name"
      responses:
        '204':
          description: Successfully deleted the service account
        default:
          "$ref": "#/responses/apierror"

  "/namespaces":
    parameters:
      - $ref: "#/parameters/kube-token"
      - $ref: "#/parameters/kube-api-url"
      - $ref: "#/parameters/kube-ca-cert"
    get:
      summary: Lists all namespaces
      description: |
        Used to list namespaces
      responses:
        '200':
          "$ref": "#/responses/namespace"
        default:
          "$ref": "#/responses/apierror"

  "/namespaces/{name}":
    parameters:
      - $ref: "#/parameters/kube-token"
      - $ref: "#/parameters/kube-api-url"
      - $ref: "#/parameters/kube-ca-cert"
    get:
      summary: Retrieves a namespace
      description: |
        Used to get a namespace
      parameters:
        - "$ref": "#/parameters/name"
      responses:
        '200':
          "$ref": "#/responses/namespace"
        default:
          "$ref": "#/responses/apierror"

    put:
      summary: Create a new namespace
      description: |
        Used to create a new namespace and optionally add a list of service accounts as admins
      parameters:
        - "$ref": "#/parameters/namespace-definition"
        - "$ref": "#/parameters/name"
      responses:
        '200':
          "$ref": "#/responses/namespace"
        default:
          "$ref": "#/responses/apierror"

    delete:
      summary: Responsible for deleting a namespace
      description: |
        Deletes a namespace
      parameters:
        - "$ref": "#/parameters/name"
      responses:
        '204':
          description: Successfully deleted the namespace
        default:
          "$ref": "#/responses/apierror"

  "/versions/{namespace}":
    parameters:
      - $ref: "#/parameters/kube-token"
      - $ref: "#/parameters/kube-api-url"
      - $ref: "#/parameters/kube-ca-cert"
    get:
      summary: Get all deployed image versions
      description: |
        Used to get the versions of all images deployed in a pod within a specified namespace
      parameters:
        - "$ref": "#/parameters/namespace"
      responses:
        '200':
          "$ref": "#/responses/imagetags"
        default:
          "$ref": "#/responses/apierror"
    post:
      summary: Get deployed versions of a given image
      description: |
        Used to get the versions of an image deployed in a pod within a specified namespace
      parameters:
        - "$ref": "#/parameters/namespace"
        - "$ref": "#/parameters/imageuri"
      responses:
        '200':
          "$ref": "#/responses/imagetags"
        default:
          "$ref": "#/responses/apierror"

definitions:
  APIError:
    description: Is a generic error event returned when the we have an internal error
    type: object
    properties:
      reason:
        description: A human readable description used to define what error has occured
        type: string
      detail:
        description: Additional details related to the error
        type: string
    required:
      - reason

  Object:
    description: The definition of a object
    type: object
    properties:
      name:
        description: A globally unique human readible resource name
        type: string
      signature:
        description: A cryptographic signature used to verify the request payload
        type: string
    required:
      - name

  NamespaceSpec:
    description: The definitions for a namespace
    type: object
    properties:
      name:
        description: The name of the namespace
        type: string
      service_accounts:
        "$ref": "#/definitions/ServiceAccountList"
    required:
      - spec

  Namespace:
    description: The resource definition for a namespace in the cluster
    type: object
    allOf:
      - "$ref": "#/definitions/Object"
    properties:
      spec:
        "$ref": "#/definitions/NamespaceSpec"
    required:
      - spec

  NamespaceList:
    description: A list of namespaces found
    type: object
    properties:
      items:
        type: array
        items:
          "$ref": "#/definitions/Namespace"

  ServiceAccountSpec:
    description: The resource specification of a service account
    type: object
    properties:
      name:
        description: The name of this service account
        type: string
      namespace:
        description: The namespace this service account is in
        type: string
      token:
        description: The token associated with the service account
        type: string
    required:
      - name

  ServiceAccount:
    description: A service account
    type: object
    allOf:
      - "$ref": "#/definitions/Object"
    properties:
      spec:
        "$ref": "#/definitions/ServiceAccountSpec"
    required:
      - spec

  ServiceAccountList:
    description: A list of service accounts
    type: object
    properties:
      items:
        type: array
        items:
          "$ref": "#/definitions/ServiceAccountSpec"

  GlobalServiceAccount:
    description: A global service account
    type: object
    allOf:
      - "$ref": "#/definitions/Object"
    properties:
      spec:
        "$ref": "#/definitions/GlobalServiceAccountSpec"
    required:
      - spec

  GlobalServiceAccountSpec:
    description: The resource specification of a global service account
    type: object
    properties:
      name:
        description: The name of the global service account
        type: string
    required:
      - name

  ImageUri:
    description: Docker image URI
    type: string

  ImageUriList:
    description: A list of Docker image URIs
    type: object
    properties:
      items:
        type: array
        items:
          "$ref": "#/definitions/ImageUri"

  ImageTag:
    description: Docker image version tag
    type: string

  ImageTagList:
    description: A list of Docker image version tags
    type: object
    properties:
      items:
        type: array
        items:
          "$ref": "#/definitions/ImageTag"
