---
swagger: '2.0'
info:
  contact:
    name: admin@appvia.io
    url: https://github.com/appvia/hub-kubernetes-agent
    email: support@appvia.io
  description: an agent used to provision and configure Kubernetes resources
  title: hub-kubernetes-agent
  version: v1beta
schemes:
  - http
securityDefinitions:
  apikey:
    type: apiKey
    in: header
    name: x-token
basePath: "/api/hub.appvia.io/v1beta"
consumes:
  - application/json
produces:
  - application/json

responses:
  apierror:
    description: A generic erorr returned by the api
    schema:
      "$ref": "#/definitions/APIError"
  notfound:
    description: The resource does not exist
  service-account:
    description: Returning the status of a service account
    schema:
      "$ref": "#/definitions/ServiceAccount"
  service-accounts:
    description: Returning a list of service accounts
    schema:
      "$ref": "#/definitions/ServiceAccountList"
  namespace:
    description: The specification of a namespace in the cluster
    schema:
      "$ref": "#/definitions/Namespace"
  namespaces:
    description: A collection namespaces found in the cluster
    schema:
      "$ref": "#/definitions/NamespaceList"

parameters:
  name:
    name: name
    description: The name of the namespace or service account you are acting upon
    in: path
    type: string
    required: true
  namespace:
    name: namespace
    description: The namespace of the service account
    in: path
    type: string
    required: true
  namespace-definition:
    name: namespace
    description: The definition of a namespace
    in: body
    schema:
      "$ref": "#/definitions/Namespace"
    required: true
  service-account-definition:
    name: service-account
    description: The definition of a service account
    in: body
    schema:
      "$ref": "#/definitions/ServiceAccount"
    required: true

paths:
  "/healthz":
    get:
      summary: Get health of Agent
      description: |
        Returns health and status information of the API daemon and
        related components such as the runtime.
      tags:
        - health
      responses:
        '200':
          description: Success
        default:
          "$ref": "#/responses/apierror"

  "/service-accounts/{namespace}":
    get:
      summary: Retrieves a list of service accounts from within the specified namespace
      description: |
        Used to retrieve a list of service accounts from within the specified namespace
      parameters:
        - "$ref": "#/parameters/namespace"
      responses:
        '200':
          "$ref": "#/responses/service-accounts"
        default:
          "$ref": "#/responses/apierror"

  "/service-accounts/{namespace}/{name}":
    get:
      summary: Retrieves a service account
      description: |
        Retrieves a service account
      parameters:
        - "$ref": "#/parameters/namespace"
        - "$ref": "#/parameters/name"
      responses:
        '200':
          "$ref": "#/responses/service-account"
        '404':
          "$ref": "#/responses/apierror"
        default:
          "$ref": "#/responses/apierror"

    post:
      summary: Creates a service account
      description: |
        Used to create a service account within a specified namespace
      parameters:
        - "$ref": "#/parameters/namespace"
        - "$ref": "#/parameters/name"
        - "$ref": "#/parameters/service-account-definition"
      responses:
        '200':
          "$ref": "#/responses/service-account"
        default:
          "$ref": "#/responses/apierror"

    delete:
      summary: Deletes a service account from the namespace
      description: |
        Used to delete a service account
      parameters:
        - "$ref": "#/parameters/namespace"
        - "$ref": "#/parameters/name"
      responses:
        '200':
          "$ref": "#/responses/service-account"
        default:
          "$ref": "#/responses/apierror"

  "/namespaces/{name}":
    post:
      summary: Create a new namespace
      description: |
        Used to create a new namespace
      parameters:
        - "$ref": "#/parameters/namespace-definition"
        - "$ref": "#/parameters/name"
      responses:
        '200':
          "$ref": "#/responses/namespace"
        default:
          "$ref": "#/responses/apierror"

    delete:
      summary: Responsible for deleting a namespace
      description: |
        Deletes a namespace
      parameters:
        - "$ref": "#/parameters/namespace-definition"
        - "$ref": "#/parameters/name"
      responses:
        '200':
          description: Successfully deleted the namespace
        default:
          "$ref": "#/responses/apierror"

definitions:
  APIError:
    description: Is a generic error event returned when the we have an internal error
    type: object
    properties:
      reason:
        description: A human readable description used to define what error has occured
        type: string
      detail:
        description: Additional details related to the error
        type: string
    required:
      - reason

  Object:
    description: The definition of a object
    type: object
    properties:
      name:
        description: A globally unique human readible resource name
        type: string
      signature:
        description: A cryptographic signature used to verify the request payload
        type: string
    required:
      - name

  NamespaceSpec:
    description: The definitions for a namespace
    type: object
    properties:
      name:
        description: The name of the namespace
        type: string
    required:
      - name

  Namespace:
    description: The resource definition for a namespace in the cluster
    type: object
    allOf:
      - "$ref": "#/definitions/Object"
    properties:
      spec:
        "$ref": "#/definitions/NamespaceSpec"
    required:
      - spec

  NamespaceList:
    description: A list of namespaces found
    type: object
    allOf:
      - "$ref": "#/definitions/Object"
    properties:
      items:
        type: array
        items:
          "$ref": "#/definitions/Namespace"

  ServiceAccountSpec:
    description: The resource specification of a service account
    type: object
    properties:
      name:
        description: The name of the service account
        type: string
      token:
        description: The token associated with the service account
        type: string
    required:
      - name

  ServiceAccount:
    description: The resource definition for a service account
    type: object
    allOf:
      - "$ref": "#/definitions/Object"
    properties:
      spec:
        "$ref": "#/definitions/ServiceAccountSpec"
    required:
      - spec

  ServiceAccountList:
    description: A list of service accounts
    type: object
    allOf:
      - "$ref": "#/definitions/Object"
    properties:
      items:
        type: array
        items:
          "$ref": "#/definitions/ServiceAccount"

